[build]
  command = "npm install && npx prisma generate"
  publish = "public" # Netlify needs a publish directory, even if empty

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
